name: Test
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v**"
  pull_request:
jobs:
  test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run go test
        run: make test-cov
      - name: Generate test badge
        if: github.ref == 'refs/heads/main'
        uses: GoTestTools/limgo-badge-action@v1.0.1
        with:
          limgo_file: test.out
          limgo_file_format: tab
          badge_name: limgo-badge.png
          repo: github.com/GoTestTools/limgo
          branch: limgo-badge
          github_token: ${{ secrets.GH_TOKEN }}
          github_token_owner: engelmi
